# Generated by Django 3.2.13 on 2022-06-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifact_generator', '0002_auto_20220614_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactDesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('flower', models.CharField(default='', max_length=255)),
                ('feather', models.CharField(default='', max_length=255)),
                ('glass', models.CharField(default='', max_length=255)),
                ('cup', models.CharField(default='', max_length=255)),
                ('head', models.CharField(default='', max_length=255)),
                ('two_set_buff', models.CharField(default='', max_length=255, unique=True)),
                ('four_set_buff', models.CharField(default='', max_length=255, unique=True)),
                ('desc', models.CharField(default='', max_length=255, unique=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('sc', '简体中文')], default='en', max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='four_set_buff',
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='two_set_buff',
        ),
    ]
