# Generated by Django 3.2.13 on 2022-06-16 04:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artifact_generator', '0004_auto_20220615_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifactdesc',
            name='artifact',
        ),
        migrations.AddField(
            model_name='artifactdesc',
            name='contribution',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artifactdesc',
            name='production',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='production',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='artifactdesc',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('zh', '简体中文')], default='en', max_length=255, unique=True),
        ),
    ]
