# Generated by Django 3.2.13 on 2022-06-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifact_generator', '0005_auto_20220615_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifactdesc',
            name='desc',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='artifactdesc',
            name='four_set_buff',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='artifactdesc',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('zh', '简体中文')], default='en', max_length=255),
        ),
        migrations.AlterField(
            model_name='artifactdesc',
            name='two_set_buff',
            field=models.CharField(default='', max_length=255),
        ),
    ]
