# Generated by Django 3.2.13 on 2022-06-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifact_generator', '0007_artifactdesc_img_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifactdesc',
            name='desc',
        ),
        migrations.AddField(
            model_name='artifactdesc',
            name='cup_desc',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='artifactdesc',
            name='feather_desc',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='artifactdesc',
            name='flower_desc',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='artifactdesc',
            name='glass_desc',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='artifactdesc',
            name='head_desc',
            field=models.CharField(default='', max_length=255),
        ),
    ]
