const en = {
  navbar: {
    home: "Home",
    sign_up: "SIGN UP",
    login: "LOGIN",
    log_out: "LOG OUT",
    artifact_generator: "Artifact Generator",
    damage_calculator: "Damage Calculator",
    others: "Others",
  },
  generator_ui: {
    teyvat: "Teyvat",
    celestia: "Celestia",
    editor: "Editor",
    artifact_screenshot: "Artifact \"Screenshot\"",
    artifact_position: "Artifact Position",
    main_property: "Main Property",
    secondary_property: "Secondary Property",
    generate: "Generate",
    not_selected: "Not Selected",
    percent: "Percentage",
    allow_blank: "Allow Blank Fields?",
    artifact_photo: "Artifact Photo",
    artifact_title: "Artifact Title",
    main_property_value: "Main Property Value",
    desc_title: "Description Title",
    desc: "Description (Max 7 Lines)",
    owner: "Owner",
    preview: "Preview",
    preview_photo: "Preview Photo",
    modify_crop: "Modify Crop",
    clear: "Clear Fields",
  },
  artifact_props: {
    atk: "ATK",
    atk_percent: "ATK Percentage",
    def: "DEF",
    def_percent: "DEF Percentage",
    hp: "HP",
    hp_percent: "HP Percentage",
    ctk_rate: "CRIT Rate",
    ctk_dmg: "CRIT DMG",
    ele_mastery: "Elemental Mastery",
    recharge_rate: "Energy Recharge",
    heal_buff: "Healing Bonus",
    phy_buff: "Physical DMG Bonus",
    pyro_buff: "Pyro DMG Bonus",
    electro_buff: "Electro DMG Bonus",
    cryo_buff: "Cryo DMG Bonus",
    hydro_buff: "Hydro DMG Bonus",
    anemo_buff: "Anemo DMG Bonus",
    geo_buff: "Geo DMG Bonus",
  },
  artifact_positions: {
    flower: "Flower of Life",
    feather: "Plume of Death",
    sand: "Sand of Eon",
    goblet: "Goblet of Eonothem",
    head: "Circlet of Logos",
  }
}

export default en;
