const zh = {
  navbar: {
    home: "主页",
    sign_up: "注册",
    login: "登录",
    artifact_generator: "圣遗物生成器",
    damage_calculator: "边际伤害计算",
    others: "其他",
  },
  generator_ui: {
    teyvat: "提瓦特",
    celestia: "天空岛",
    editor: "圣遗物编辑器",
    artifact_screenshot: "圣遗物 \"截图\"",
    artifact_position: "圣遗物位置",
    main_property: "主词条",
    secondary_property: "副词条",
    generate: "生成",
    not_selected: "未选择",
    percent: "百分比",
    allow_blank: "允许空位？",
    artifact_photo: "圣遗物头像",
    artifact_title: "圣遗物名称",
    main_property_value: "之词条值",
    desc_title: "介绍标题",
    desc: "介绍 (最多7行)",
    owner: "佩戴者",
    preview: "预览",
    preview_photo: "预览图片",
    modify_crop: "修改裁剪",
    clear: "清除所有"
  },
  artifact_props: {
    atk: "攻击力",
    atk_percent: "攻击力百分比",
    def: "防御力",
    def_percent: "防御力百分比",
    hp: "生命值",
    hp_percent: "生命值百分比",
    ctk_rate: "暴击率",
    ctk_dmg: "暴击伤害",
    ele_mastery: "元素精通",
    recharge_rate: "元素充能效率",
    heal_buff: "治疗加成",
    phy_buff: "物理伤害加成",
    pyro_buff: "火元素伤害加成",
    electro_buff: "雷元素伤害加成",
    cryo_buff: "冰元素伤害加成",
    hydro_buff: "水元素伤害加成",
    anemo_buff: "风元素伤害加成",
    geo_buff: "岩元素伤害加成",
  },
  artifact_positions: {
    flower: "生之花",
    feather: "死之羽",
    sand: "时之沙",
    cup: "空之杯",
    head: "理之冠",
  }
}

export default zh;
