# Generated by Django 3.2.13 on 2022-06-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='genshin_server',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='genshin_uid',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.TextField(default='', max_length=255, unique=True),
        ),
    ]
